// Generated by LiveScript 1.4.0
(function(){
  var main, mainJs, ref$, out$ = typeof exports != 'undefined' && exports || this;
  main = require('./main');
  mainJs = require('./main-js');
  ref$ = out$;
  ref$.evaluateJavascript = main.evaluateJavascript;
  ref$.runTape = main.runTape;
  ref$.conditionWait = main.conditionWait;
  ref$.init = main.init;
  ref$.initJs = mainJs.initJs;
}).call(this);
